export const locations = [
    { value: "aberdeen", label: "Aberdeen", country: "Scotland" },
    { value: "armagh", label: "Armagh", country: "Northern Ireland" },
    { value: "bangor-ni", label: "Bangor - Northern Ireland", country: "Northern Ireland" },
    { value: "bangor-w", label: "Bangor - Wales", country: "Wales" },
    { value: "bath", label: "Bath", country: "England" },
    { value: "belfast", label: "Belfast", country: "Northern Ireland" },
    { value: "birmingham", label: "Birmingham", country: "England" },
    { value: "bradford", label: "Bradford", country: "England" },
    { value: "brighton & hove", label: "Brighton & Hove", country: "England" },
    { value: "bristol", label: "Bristol", country: "England" },
    { value: "cambridge", label: "Cambridge", country: "England" },
    { value: "canterbury", label: "Canterbury", country: "England" },
    { value: "carlisle", label: "Carlisle", country: "England" },
    { value: "cardiff", label: "Cardiff", country: "Wales" },
    { value: "chelmsford", label: "Chelmsford", country: "England" },
    { value: "chester", label: "Chester", country: "England" },
    { value: "chichester", label: "Chichester", country: "England" },
    { value: "colchester", label: "Colchester", country: "England" },
    { value: "coventry", label: "Coventry", country: "England" },
    { value: "derby", label: "Derby", country: "England" },
    { value: "doncaster", label: "Doncaster", country: "England" },
    { value: "dunfermline", label: "Dunfermline", country: "Scotland" },
    { value: "dundee", label: "Dundee", country: "Scotland" },
    { value: "durham", label: "Durham", country: "England" },
    { value: "edinburgh", label: "Edinburgh", country: "Scotland" },
    { value: "ely", label: "Ely", country: "England" },
    { value: "exeter", label: "Exeter", country: "England" },
    { value: "glasgow", label: "Glasgow", country: "Scotland" },
    { value: "gloucester", label: "Gloucester", country: "England" },
    { value: "hereford", label: "Hereford", country: "England" },
    { value: "inverness", label: "Inverness", country: "Scotland" },
    { value: "kingston-upon-hull", label: "Kingston-upon-Hull", country: "England" },
    { value: "lancaster", label: "Lancaster", country: "England" },
    { value: "leeds", label: "Leeds", country: "England" },
    { value: "leicester", label: "Leicester", country: "England" },
    { value: "lichfield", label: "Lichfield", country: "England" },
    { value: "lincoln", label: "Lincoln", country: "England" },
    { value: "lisburn", label: "Lisburn", country: "Northern Ireland" },
    { value: "liverpool", label: "Liverpool", country: "England" },
    { value: "london", label: "London", country: "England" },
    { value: "londonderry", label: "Londonderry", country: "Northern Ireland" },
    { value: "manchester", label: "Manchester", country: "England" },
    { value: "milton keynes", label: "Milton Keynes", country: "England" },
    { value: "newcastle-upon-tyne", label: "Newcastle-upon-Tyne", country: "England" },
    { value: "newport", label: "Newport", country: "Wales" },
    { value: "newry", label: "Newry", country: "Northern Ireland" },
    { value: "norwich", label: "Norwich", country: "England" },
    { value: "nottingham", label: "Nottingham", country: "England" },
    { value: "oxford", label: "Oxford", country: "England" },
    { value: "perth", label: "Perth", country: "Scotland" },
    { value: "peterborough", label: "Peterborough", country: "England" },
    { value: "plymouth", label: "Plymouth", country: "England" },
    { value: "portsmouth", label: "Portsmouth", country: "England" },
    { value: "preston", label: "Preston", country: "England" },
    { value: "ripon", label: "Ripon", country: "England" },
    { value: "salford", label: "Salford", country: "England" },
    { value: "salisbury", label: "Salisbury", country: "England" },
    { value: "sheffield", label: "Sheffield", country: "England" },
    { value: "southampton", label: "Southampton", country: "England" },
    { value: "southend-on-sea", label: "Southend-on-Sea", country: "England" },
    { value: "st albans", label: "St Albans", country: "England" },
    { value: "st asaph", label: "St Asaph", country: "Wales" },
    { value: "st davids", label: "St Davids", country: "Wales" },
    { value: "stirling", label: "Stirling", country: "Scotland" },
    { value: "stoke on trent", label: "Stoke on Trent", country: "England" },
    { value: "sunderland", label: "Sunderland", country: "England" },
    { value: "swansea", label: "Swansea", country: "Wales" },
    { value: "truro", label: "Truro", country: "England" },
    { value: "wakefield", label: "Wakefield", country: "England" },
    { value: "wells", label: "Wells", country: "England" },
    { value: "westminster", label: "Westminster", country: "England" },
    { value: "winchester", label: "Winchester", country: "England" },
    { value: "wolverhampton", label: "Wolverhampton", country: "England" },
    { value: "worcester", label: "Worcester", country: "England" },
    { value: "wrexham", label: "Wrexham", country: "Wales" },
    { value: "york", label: "York", country: "England" }
  ];  